version: '3'

services:
    redis-helpers:
        build:
            context: .
            dockerfile: Dockerfile
        image: "stephenneal/redis-helpers:latest"
        env_file: .env.docker
        container_name: redis-helpers
        tty: true
        volumes:
            - redis-helpers:/var/www
        depends_on:
            - redis-helpers-cache
        networks:
            - redis-helpers-network

    redis-helpers-cache:
        container_name: redis-helpers-cache
        image: redis:7-alpine
        command: ["redis-server", "--appendonly yes", "--port 9736"]
        ports:
            - "9736:9736"
        volumes:
            - redis-helpers-cache:/data
        networks:
            - redis-helpers-network


# Networks
networks:
    redis-helpers-network:
        driver: bridge

# Volumes
volumes:
    redis-helpers:
    redis-helpers-cache:
