version: '3'

services:
    package:
        build:
            context: .
            dockerfile: Dockerfile
        image: stephenneal/redis-helpers:dev
        container_name: package
        command: "--filter PredisClientTest::delete_single_key"
        restart: "no"
        tty: true
        working_dir: /var/www
        volumes:
            - package:/var/www
        depends_on:
            - cache
        networks:
            - package-network

    cache:
        container_name: cache
        image: redis:6-alpine
        command: [ "redis-server", "--appendonly", "yes" ]
        ports:
            - "6379:6379"
        volumes:
            - cache:/data
        networks:
            - package-network


# Networks
networks:
    package-network:
        driver: bridge

# Volumes
volumes:
    package:
    cache:
